feat: Add alt mach v2 mainnet support
alt-research/mach-avs-operator-setup pull request #38
Opened 2024-06-19 03:44 UTC by fyInALT

2024-06-19 07:44 UTC, bb111189 approved these changes

2024-06-21 03:43 UTC, bb111189 submitted a review, later dismissed

2024-06-21 04:14 UTC, bb111189 approved these changes

2024-06-21 08:52 UTC, renlulu approved these changes

2024-06-24 09:11 UTC, jinnzy approved these changes

2024-06-26 06:34 UTC, bb111189 requested changes

2024-06-26 06:34 UTC, bb111189 commented on ethereum/mach-avs/README.md
> +* [Altlayer Multi-Mach](./altlayer-multi-mach/README.md)
```suggestion
* [Altlayer Mach (OP Mainnet and Arbitrum One)](./altlayer-multi-mach/README.md)
```

2024-06-26 06:34 UTC, bb111189 commented on ethereum/mach-avs/README.md
>  * [Optimism Mainnet](./optimism/README.md)
```suggestion
```

2024-06-26 07:25 UTC, renlulu approved these changes

2024-06-26 07:58 UTC, bb111189 approved these changes

2024-06-26 08:12 UTC, merged